name: JarzLab
options:
  bundleIdPrefix: com.antonpenkov
  deploymentTarget:
    iOS: "17.0"
targets:
  JarzLab:
    type: application
    platform: iOS
    sources:
      - JarzLab
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.antonpenkov.jarzlab
        DEVELOPMENT_TEAM: 3UHRLQ9522
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        INFOPLIST_KEY_CFBundleDisplayName: JarzLab
        TARGETED_DEVICE_FAMILY: "1"
        SWIFT_VERSION: "5.9"
